version: "3.1"

services:
  web:
    image: itzg/rcon
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      # is referring to the hostname of 'mc' compose service below
      RWA_RCON_HOST: forge
      # needs to match the password configured for the container, which is 'minecraft' by default
      RWA_RCON_PASSWORD: minecraft
    ports:
      - 25566:4326
      - 25567:4327
  forge:
    image: itzg/minecraft-server:java17
    ports:
      - 25565:25565
    volumes:
      - "./server:/data"
      - "./resource/mods:/mods"
      - "./resource/world:/world"
    environment:
      EULA: "TRUE"
      VERSION: "1.18.2"
      TYPE: "FORGE"
      FORGE_INSTALLER: "forge-1.18.2-40.1.51-installer.jar"
      MODS: "/mods"
      WORLD: "/world"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "5"
      FORCE_GAMEMODE: "true"
      HARDCORE: "false"
      MODE: "survival"
      PVP: "true"
      ONLINE_MODE: "false"
      ALLOW_FLIGHT: "true"
      SERVER_NAME: "DDServer"
      MOTD: "DDServer"
      MEMORY: "12G"
      # WHITELIST: ""
      OPS: "X_w_X"
      BROADCAST_CONSOLE_TO_OPS: "false"
      BROADCAST_RCON_TO_OPS: "false"
    restart: always
